### ISSUE TITLE
[FEATURE REQUEST] Add other commonly used features

### ISSUE THREAD

**Issue by jonjoncardoso** [jonjoncardoso/quarto-template-for-university-courses#4]
Things I am now using on my pages and which have not been replicated on the template yet:

- [ ] Add a `404.qmd` page
- [ ] Add the template of a `syllabus.qmd` ([example](https://lse-dsi.github.io/DS105/2024/autumn-term/syllabus.html))
- [ ] Add more generic path capture to `project` > `render` attribute. This avoids having to edit the `quarto.yml` all the time. For example:
  ```yaml
  project:
    ...
    render:
      - "index.qmd"
      - "blog/*.qmd"
      - "blog/posts/*.qmd"
      - "404.qmd"
      - "2024/*/*.qmd"
      - "2024/*/**/*.qmd"
  ```
